
export interface User {
  id: string;
  name: string;
  handle: string;
  deviceType: 'mobile' | 'desktop';
  score: number;
  lastPulse: number;
  isVerified: boolean;
  pingCount: number;
  // Team identifier for the user's selected NFL team
  team?: string;
}

export interface GameState {
  roomCode: string;
  startTime: number;
  isActive: boolean;
  globalScoreMultiplier: number;
  // Live game state tracking for Super Bowl events
  quarter: string;
  time: string;
  scoreHome: number;
  scoreAway: number;
}

export interface ChatMessage {
  id: string;
  userId: string;
  userName: string;
  text: string;
  timestamp: number;
  // Flag to differentiate between human and AI analyst messages
  isAI?: boolean;
}

// Interface for a single proposition bet generated by Gemini
export interface PropBet {
  id: string;
  question: string;
  category: string;
  options: string[];
  resolved: boolean;
  winner?: string;
}

// Interface for a user's wager on a specific prop bet
export interface UserBet {
  id: string;
  userId: string;
  betId: string;
  selection: string;
  timestamp: number;
}
